### ISSUE TITLE
Pass and return parameters from go to php

### ISSUE THREAD

**Issue by anjapadu** [mikespook/goemphp#13]
Is it possible to pass parameters from go to php and return a value from php to go whit this library? If yes could be so kind to tell me how?

**Comment by mikespook** [comment]
You can check the code here https://github.com/mikespook/goemphp/blob/master/php_test.go#L101.

However, this project was designed and written in 2011 for my personal experiment, I'd like to say this project already dead long time ago. So, please use it as your own risk.

And there are plenty similar projects on Github now. If you want to use PHP in Golang project seriously, you'd better use the other continuing maintained projects other than this experiment one.

Thanks & Cheers!
